// poc/auth-sdk/examples/vue-example.vue
<template>
  <div>
    <h1>My App</h1>

    <!-- Public content -->
    <div v-if="!isAuthenticated">
      <h2>Login</h2>
      <form @submit.prevent="handleLogin">
        <div>
          <label for="email">Email</label>
          <input type="email" id="email" v-model="email" required />
        </div>
        <div>
          <label for="password">Password</label>
          <input type="password" id="password" v-model="password" required />
        </div>
        <div v-if="error" class="error">{{ error }}</div>
        <button type="submit" :disabled="loading">
          {{ loading ? "Logging in..." : "Login" }}
        </button>
      </form>
    </div>

    <!-- Protected content with directive -->
    <div v-auth:authenticated>
      <h2>Dashboard</h2>
      <p>Welcome, {{ user?.email }}</p>

      <!-- Role-based content -->
      <div v-auth:role="'admin'">
        <h3>Admin Panel</h3>
        <p>This content is only visible to admins</p>
      </div>

      <!-- Permission-based content -->
      <div v-auth:permission="'manage_users'">
        <h3>User Management</h3>
        <p>
          This content is only visible to users with manage_users permission
        </p>
      </div>

      <button @click="handleLogout">Logout</button>
    </div>
  </div>
</template>

<script>
import { defineComponent, ref } from "vue";
import { useAuth } from "../adapters/vue";

export default defineComponent({
  name: "App",
  setup() {
    const { client, user, isAuthenticated } = useAuth();
    const email = ref("");
    const password = ref("");
    const error = ref("");
    const loading = ref(false);

    const handleLogin = async () => {
      loading.value = true;
      error.value = "";

      try {
        await client.login({
          email: email.value,
          password: password.value,
        });
        // Redirect or handle successful login
      } catch (err) {
        error.value = "Invalid credentials";
      } finally {
        loading.value = false;
      }
    };

    const handleLogout = () => {
      client.logout();
    };

    return {
      user,
      isAuthenticated,
      email,
      password,
      error,
      loading,
      handleLogin,
      handleLogout,
    };
  },
});
</script>

// poc/auth-sdk/examples/react-example.tsx
import React, { useState } from "react";
import {
  createAuthClient,
  AuthProvider,
  useAuth,
  ProtectedRoute,
} from "../index";

// Create the auth client
const authClient = createAuthClient({
  apiUrl: "https://api.example.com/auth",
  tokenStorage: "localStorage",
  autoRefresh: true,
});

// Example login component
function LoginForm() {
  const { client } = useAuth();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError("");

    try {
      await client.login({ email, password });
      // Redirect or handle successful login
    } catch (err) {
      setError("Invalid credentials");
    } finally {
      setLoading(false);
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      <div>
        <label htmlFor="email">Email</label>
        <input
          type="email"
          id="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          required
        />
      </div>
      <div>
        <label htmlFor="password">Password</label>
        <input
          type="password"
          id="password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          required
        />
      </div>
      {error && <div className="error">{error}</div>}
      <button type="submit" disabled={loading}>
        {loading ? "Logging in..." : "Login"}
      </button>
    </form>
  );
}

// Example protected component
function AdminDashboard() {
  const { user, client } = useAuth();

  const handleLogout = () => {
    client.logout();
  };

  return (
    <div>
      <h1>Admin Dashboard</h1>
      <p>Welcome, {user?.email}</p>
      <button onClick={handleLogout}>Logout</button>
    </div>
  );
}

// Example App
function App() {
  return (
    <AuthProvider client={authClient}>
      <div>
        <h1>My App</h1>

        {/* Public route */}
        <div>
          <h2>Public Page</h2>
          <LoginForm />
        </div>

        {/* Protected route */}
        <ProtectedRoute
          element={<AdminDashboard />}
          requiredRoles={["admin"]}
          redirectUrl="/login"
        />
      </div>
    </AuthProvider>
  );
}

export default App;
